import {
  FaBaby,
  FaBed,
  FaBicycle,
  FaBolt,
  FaBook,
  FaBreadSlice,
  FaBroom,
  FaBug,
  FaCalculator,
  FaCalendarAlt,
  FaCamera,
  FaCar,
  FaChalkboardTeacher,
  FaCheese,
  FaCouch,
  FaCut,
  FaDesktop,
  FaDumbbell,
  FaFilm,
  FaGavel,
  FaGem,
  FaGlasses,
  FaHammer,
  FaHandHoldingHeart,
  FaHardHat,
  FaHome,
  FaHotel,
  FaLeaf,
  FaMobileAlt,
  FaPaintRoller,
  FaPaw,
  FaPen,
  FaPills,
  FaPlane,
  FaRing,
  FaRobot,
  FaSchool,
  FaSeedling,
  FaShieldAlt,
  FaShoePrints,
  FaSpa,
  FaStar,
  FaStore,
  FaTaxi,
  FaTooth,
  FaTshirt,
  FaUserMd,
  FaUtensils,
  FaWineBottle,
  FaWrench,
} from 'react-icons/fa'

export const iconMap = {
  'fa-user-md': FaUserMd,
  'fa-dumbbell': FaDumbbell,
  'fa-cut': FaCut,
  'fa-home': FaHome,
  'fa-utensils': FaUtensils,
  'fa-store': FaStore,
  'fa-school': FaSchool,
  'fa-chalkboard-teacher': FaChalkboardTeacher,
  'fa-hotel': FaHotel,
  'fa-plane': FaPlane,
  'fa-calculator': FaCalculator,
  'fa-gavel': FaGavel,
  'fa-couch': FaCouch,
  'fa-calendar-alt': FaCalendarAlt,
  'fa-camera': FaCamera,
  'fa-bread-slice': FaBreadSlice,
  'fa-pills': FaPills,
  'fa-car': FaCar,
  'fa-mobile-alt': FaMobileAlt,
  'fa-gem': FaGem,
  'fa-tshirt': FaTshirt,
  'fa-spa': FaSpa,
  'fa-tooth': FaTooth,
  'fa-paw': FaPaw,
  'fa-shield-alt': FaShieldAlt,
  'fa-broom': FaBroom,
  'fa-bug': FaBug,
  'fa-wrench': FaWrench,
  'fa-bolt': FaBolt,
  'fa-hammer': FaHammer,
  'fa-paint-roller': FaPaintRoller,
  'fa-baby': FaBaby,
  'fa-hand-holding-heart': FaHandHoldingHeart,
  'fa-seedling': FaSeedling,
  'fa-pen': FaPen,
  'fa-glasses': FaGlasses,
  'fa-wine-bottle': FaWineBottle,
  'fa-cheese': FaCheese,
  'fa-leaf': FaLeaf,
  'fa-bicycle': FaBicycle,
  'fa-taxi': FaTaxi,
  'fa-film': FaFilm,
  'fa-book': FaBook,
  'fa-robot': FaRobot,
  'fa-shoe-prints': FaShoePrints,
  'fa-ring': FaRing,
  'fa-hard-hat': FaHardHat,
  'fa-bed': FaBed,
  'fa-desktop': FaDesktop,
}

export const fallbackIcon = FaStar
